"""Add is_deleted fields

Revision ID: 0acc3ce3ea9a
Revises: 9a30f14f952a
Create Date: 2025-04-01 00:19:05.994287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0acc3ce3ea9a'
down_revision = '9a30f14f952a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('book_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_analysis', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
